### ISSUE TITLE
Missing `mpii-multiperson` folder

### ISSUE THREAD

**Issue by x65han** [iqbalu/PoseTrack-CVPR2017#11]
Trying to run `demo_multiperson` in Matlab and got the following response. I have run `download_models.sh` in `data` folder, but I do not have` data/mpii-multiperson folder` for some reason. Where can I get this `mpii-multiperson folder`? Thank you!

```
Error using load
Unable to read file '/Users/johnson/Desktop/RA/PoseTrack-CVPR2017/data/mpii-multiperson/images/test/annolist'.
No such file or directory.
```

**Comment by umariqb** [comment]
You should run demo_posetrack.m instead.
