### ISSUE TITLE
undefined reference to `GRBException::getMessage[abi:cxx11]() const'

### ISSUE THREAD

**Issue by yulijun1234** [iqbalu/PoseTrack-CVPR2017#13]
Ubuntu 16.04,Matlab 2014a ,caffe,gurobi752,cuda 8.0 installed succesfully.
when i run " make pt-solver-callback",
there comes this problem:  
CMakeFiles/pt-solver-callback.dir/src/pose-track/research/pt-solver-callback.cxx.o: In function `main':
pt-solver-callback.cxx:(.text+0x167e): undefined reference to `GRBException::getMessage[abi:cxx11]() const'
CMakeFiles/pt-solver-callback.dir/src/pose-track/research/pt-solver-callback.cxx.o: In function `void andres::ilp::Gurobi<double>::addConstraint<unsigned long const*, double const*>(unsigned long const*, unsigned long const*, double const*, double, double)':

i can't find any references on the Internet, hope you can give me some advice!thank you!

**Comment by umariqb** [comment]
I think the version of Gurobi is the problem. We used Gurobi 6.0.x and it's possible that the function 'GRBException::getMessage' is not there anymore in the latest version.

**Comment by yulijun1234** [comment]
Thank you so much for your advice ! This problem has been solved by downgrade the version of gcc and g++, i change the version from gcc 5.4 to gcc 4.8,but it comes with some other problems.....
1. the url in ./download_models.sh  i cannot visit, so i don't have the models. But i tried this with another folder named pairwise.....
2.when i open matlab, run the demo_poseTrack: "MATLAB has encountered an internal problem and needs to close, The unsaved information you were working on may be lost. we are sorry for the inconvenience, click End now to close MATLAB now......" matlab shut down....

i confirmed make mattest, it works right......hope you share your advice with me !

**Comment by umariqb** [comment]
No idea why matlab is crashing. It shouldn't be.
