### ISSUE TITLE
Error using hdf5writec

### ISSUE THREAD

**Issue by yulijun1234** [iqbalu/PoseTrack-CVPR2017#14]
Hi. i succesfully installed  HDF5 1.8  CMake  C++ 11  CUDA 8.0  matlab2014a and made the project successfully, but there are some problems. The first is i can't open matlab using ./start_matlab.sh, instead i open matlab in the path of my matlab installation , and run sudo ./matlab.sh under bin. i don't know whether it matters??? when i tried the models: startup and demo_multiperson, it occured some problems......
Cleared 0 solvers and 0 stand-alone nets
save dir /home/yulijun/PoseTrack-CVPR2017/deepcut/data/mpii-multiperson/scoremaps/test
testing from net file /home/yulijun/PoseTrack-CVPR2017/deepcut/data/caffe-models/ResNet-101-mpii-multiperson.caffemodel
deepcut: test (MPII multiperson test) 2/1758
Cleared 0 solvers and 1 stand-alone nets
test_spatial_hist()
expidx: 1
firstidx: 2
nImgs: 1
/bin/bash: /home/yulijun/Downloads/MATLAB/bin/glnxa64/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4)

malloc: unknown:0: assertion botched

free: called with unallocated block argument
last command: (null)
Aborting...mkdir -p /home/yulijun/PoseTrack-CVPR2017/deepcut/data//mpii-multiperson/multicut/: Aborted
multicutDir: /home/yulijun/PoseTrack-CVPR2017/deepcut/data//mpii-multiperson/multicut/
/bin/bash: /home/yulijun/Downloads/MATLAB/bin/glnxa64/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4)

malloc: unknown:0: assertion botched

free: called with unallocated block argument
last command: (null)
Aborting...mkdir -p /home/yulijun/PoseTrack-CVPR2017/deepcut/data/mpii-multiperson/multicut/vis: Aborted
Loading spatial model from /home/yulijun/PoseTrack-CVPR2017/deepcut/data/pairwise
recompute 1
imgidx: 2
loading features... done!
im_name im00044_1
Warning: Image is too big to fit on screen; displaying at 67% 
> In imuitools/private/initSize at 71
  In imshow at 282
  In test_spatial_app_neighbour at 210
  In demo_multiperson at 12 
number of detections before 1018 after 1018
crop rectangle (x, y, width, height): (1 1 1519 681)
preserve 80/3960 detections
compute pairwise across parts prob
Accuracy = 94.5% (6048/6400)
Accuracy = 93.75% (6000/6400)
Accuracy = 75% (4800/6400)
Accuracy = 99.5% (6368/6400)
Accuracy = 79.75% (5104/6400)
Accuracy = 68% (4352/6400)
save problem
Error using hdf5writec
Call to HDF5 library failed (fileCreation): "createHDF5File: Couldn't create file.".

Error in hdf5write (line 138)
hdf5writec(file, details, varargin{dset_idx});

Error in marray_save (line 15)
hdf5write(file_name, dataset_name, M, 'WriteMode', write_mode);

Error in test_spatial_app_neighbour (line 395)
            marray_save(problemFname, dataName, dets.unProb, write_mode);

Error in demo_multiperson (line 12)
test_spatial_app_neighbour(experiment_index, image_index, 1, true, true);

PS: i installed the hdf5 1.8.18 after building caffe and matlab, and solver.....

hope you give me your advice ,Thank you very much!

**Comment by umariqb** [comment]
You should use demo_posetrack, in the main directory. Not "demo_multiperson"
