### ISSUE TITLE
I can't download  pairwise models 

### ISSUE THREAD

**Issue by afanti986** [iqbalu/PoseTrack-CVPR2017#16]
Ｈi.
I can not access this URL "http://pages.iai.uni-bonn.de/iqbal_umar/PoseTrack/data/models.tar.gz".　Maybe this site is invalid?

**Comment by umariqb** [comment]
Hi, 

I am sorry for the inconvenience. Our department is moving to a new building, and all the servers are down at the moment. They should be up again in a few days.

**Comment by afanti986** [comment]
Thank you for your reply.

Ｂｕｔ now the entire project only lacks model files.Because the project is  urgent, can you please send me by other means?For example through the mailbox.

Ｔhank you very much！






At 2018-03-03 10:34:23, "Umar Iqbal" <notifications@github.com> wrote:


Hi,

I am sorry for the inconvenience. Our department is moving to a new building, and all the servers are down at the moment. They should be up again in a few days.

**Comment by umariqb** [comment]
Here you go, 
[data.zip](https://github.com/iqbalu/PoseTrack-CVPR2017/files/1779308/data.zip)

**Comment by afanti986** [comment]
Thank you very much.






At 2018-03-05 10:36:11, "Umar Iqbal" <notifications@github.com> wrote:


Here you go,
data.zip
