### ISSUE TITLE
problem with Demo_posetrack 

### ISSUE THREAD

**Issue by ghost** [iqbalu/PoseTrack-CVPR2017#17]
I stopped at "keyboard()" in function  "pt_load_dm_correspondences" which requires keyborad input.
But what should I input to continue~

Thank you very much

**Comment by umariqb** [comment]
Have you computed the correspondences using DeepMatching? It's likely that one of the files is corrupt or does not exist. Just check the file that is being processed at that time. 

I will update the error handling with an assert.

**Comment by ghost** [comment]
Thank you, I fixed this by precomputing Deep matching results
