### ISSUE TITLE
Missing 'pt_convert_people_to_struct' m file

### ISSUE THREAD

**Issue by YuliangXiu** [iqbalu/PoseTrack-CVPR2017#2]
I'd like to adapt your evaluation code to test other pose estimation frameworks' final results, but when I run **pt_eval_pose_tracking**, it stops at **pt_convert_people_to_struct** function, I can not find where is the corresponding m file. I will appreciate it if you can upload this file into this repo.

Besides, can you give a guide to demonstrate how to implement the evaluation on other pose estimation frameworks? such as CPM or LJPA, themselves have no tracking phrase and have no locreg nextreg, so only shift the caffe model can not work. How do you introduce the  BBox-tracking  strategy into other pose estimation framework to evaluation the pose tracking performance?

**Comment by iqbalu** [comment]
Added the file. So closing the issue. 

Tracking for other methods is based on bounding boxes. We first detect all persons using Faster-RCNN, and track the bounding boxes following "tracking by detection" method. Please have a look at Siyu Tang's ECCV-workshop paper for more details. Given person tracks, we estimate pose for each person using its bounding box information.

**Comment by YuliangXiu** [comment]
@iqbalu Thanks so much about your reply, it helps a lot! @iqbalu
