### ISSUE TITLE
use the detector's result as nodes, rather than joints.

### ISSUE THREAD

**Issue by OneDirection9** [iqbalu/PoseTrack-CVPR2017#3]
I want to test the performance on MOT2016, so I need to replace the nodes with detetor's results. I just wanna know how to do it. Thanks.

**Comment by iqbalu** [comment]
Please have a look at Siyu Tang's ECCV'16 workshop paper. 

From implementation point-of-view, you will have to change the solver in this case i.e., update the objective and constraints.

**Comment by OneDirection9** [comment]
Thanks for your attention. And I have found one question as follows.
I think the `x2 = x1 + r` and `y2 = y1 + r` maybe changed with `x2 = x1 + ps`, and `y2` too. Since the coordinate for point should be the center of bbox.

```matlab      
scales = dets.scale;
ps = p.patchSize * 1./scales;
r  = ps/2;
x1 = locations(:,1) - r;
y1 = locations(:,2) - r ;
x2 = x1 + r; 
y2 = y1 + r;
```

**Comment by iqbalu** [comment]
Yes, you are right.
