### ISSUE TITLE
Undefined variable Error in pt_get_spatial_features_dm.m

### ISSUE THREAD

**Issue by jin-s13** [iqbalu/PoseTrack-CVPR2017#4]
I tried to train by myself the pairwise and pt-pairwise models (`http://pages.iai.uni-bonn.de/iqbal_umar/PoseTrack/data/models.tar.gz`)

When I run pt_train_spatial_part_regr.m, some error occurs. 

`
Undefined function or variable 'fr_name1'.
Error in pt_get_spatial_features_dm (line 65)
        corres_fn = fullfile(corres_dir, [fr_name1,'_',fr_name2,'.txt']);
Error in pt_train_spatial_part_regr (line 28)
    [X_pos, X_neg] = pt_get_spatial_features_dm(expidx,cidx);
 function [X_pos, X_neg] = pt_get_spatial_features_dm(expidx,cidx)
Error: Function definitions are not permitted in this context.
`
I would appreciate it if you could fix it.

Many thanks!

**Comment by iqbalu** [comment]
To train pairwise models, you should refer to the implementation of DeepCut. For pt-pairwise models, the function pt_train_temporal_part_regr() should be used. The file is mistakenly placed in the repo and should not be used. I am removing it from the repo. 

Thanks for notifying.
