### ISSUE TITLE
Environment questions

### ISSUE THREAD

**Issue by xzha8059** [iqbalu/PoseTrack-CVPR2017#5]
hi, iqbalu, do you have the same code could run in Windows system? Thanks for your help.

**Comment by iqbalu** [comment]
Hi xzha8059, we never tried running it on windows. If you can compile the solver and DeepMatching on windows, I hope that the rest of the Matlab code should work out-of-the-box. You might only have to adjust the paths (slashes) from linux format to windows.

**Comment by xzha8059** [comment]
Hi, Iqbalu, thanks for your reply, I will try. If I can success, I will share with you.
