### ISSUE TITLE
demo_posetrack did not show any tracking results

### ISSUE THREAD

**Issue by saraershadi** [iqbalu/PoseTrack-CVPR2017#6]
Hi, 

I have run the PoseTrack code. All things is ok and all functions works. But In final step, your provided code can not track any of people in the example video frames in demo_PoseTrack. 
I debuged demo_posetrack, it is because that in function pt_vis_people line 40 , the variable 
people has 0*8 size and it is empty.
people = people(logical(corrIdxs), :);

I wonder myself although with excellent results provided  in the project page and CVPR paper, why demo code can not work properly ?

pt_vis_people only shows the original images without colorizing any of human in the images, because the size of people is empty when it is saved in the previous functions.

Thank you
Best regards
Sarah

**Comment by saraershadi** [comment]
Hi,

demo_posetrack.m works properly. :-)

Regrards
Sarah

**Comment by iqbalu** [comment]
Hi, Sara. I am glad that it worked fine now!!

**Comment by saraershadi** [comment]
Hi Iqbalu,

Your provided code is very dataset specific, I want to test it with images of campus and Shelf dataset to compare my results with yours. But really this code has lots of dependencies with the dataset.
In all sub methods and sub function really there is lots of dependencies with the dataset.
What is your propose for fast testing of this code on others dataset such as Shelf or Campus ?

Thank you
Regards
Sarah

**Comment by iqbalu** [comment]
The easiest way would be to write a wrapper to convert the annotations of Shelf/Campus dataset to our format.
